#!/usr/bin/env python
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

TOOLS_DIR = Path(__file__).resolve().parents[1]
if str(TOOLS_DIR) not in sys.path:
    sys.path.insert(0, str(TOOLS_DIR))

from _util import load_json, validate_artifact, write_json  # noqa: E402


def now_utc() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def render_content(
    rel_path: str, contract: dict[str, Any], run_id: str, packet_dir: Path
) -> bytes:
    if rel_path == "packet.json":
        payload = {
            "packet_id": contract["packet_id"],
            "run_id": run_id,
            "status": "PASS",
            "generated_at": now_utc(),
            "output_root": str(packet_dir),
        }
        return (json.dumps(payload, indent=2, sort_keys=True) + "\n").encode("utf-8")

    if rel_path == "contract.json":
        return (json.dumps(contract, indent=2, sort_keys=True) + "\n").encode("utf-8")

    if rel_path == "summary.md":
        lines = [
            f"# Golden Packet Summary: {contract['packet_id']}",
            "",
            f"- run_id: `{run_id}`",
            "- status: `PASS`",
            f"- generated_at: `{now_utc()}`",
            "",
            "Required evidence files were materialized by the deterministic harness.",
            "",
        ]
        return "\n".join(lines).encode("utf-8")

    if rel_path.endswith(".jsonl"):
        event = {
            "ts": now_utc(),
            "packet_id": contract["packet_id"],
            "run_id": run_id,
            "event": "golden_packet_materialized",
        }
        return (json.dumps(event, sort_keys=True) + "\n").encode("utf-8")

    if rel_path.endswith(".json"):
        payload = {
            "packet_id": contract["packet_id"],
            "run_id": run_id,
            "path": rel_path,
        }
        return (json.dumps(payload, indent=2, sort_keys=True) + "\n").encode("utf-8")

    if rel_path.endswith(".xml"):
        return (
            '<?xml version="1.0" encoding="UTF-8"?>\n'
            '<testsuite name="golden-packet" tests="1" failures="0">'
            '<testcase classname="golden" name="materialize_evidence"/>'
            "</testsuite>\n"
        ).encode("utf-8")

    if rel_path.endswith(".log"):
        return f"{now_utc()} INFO golden packet materialized\n".encode("utf-8")

    if rel_path.endswith(".md"):
        return f"# {rel_path}\n\nGenerated by run_golden_packet.py\n".encode("utf-8")

    return b""


def write_if_changed(path: Path, content: bytes) -> str:
    if path.exists() and path.read_bytes() == content:
        return "skipped"
    existed = path.exists()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(content)
    return "updated" if existed else "created"


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Materialize a deterministic golden packet evidence tree from a pre-contract."
    )
    parser.add_argument(
        "--contract",
        required=True,
        help="path to packet pre-contract JSON",
    )
    parser.add_argument(
        "--out-root",
        default="migration/runtime/golden_packet",
        help="base output directory for golden packet runs",
    )
    parser.add_argument(
        "--run-id",
        default=None,
        help="optional explicit run id (default generated UTC timestamp id)",
    )
    args = parser.parse_args()

    contract_path = Path(args.contract).resolve()
    out_root = Path(args.out_root).resolve()
    run_id = (
        args.run_id or f"golden-{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')}"
    )

    if not contract_path.exists():
        raise SystemExit(f"contract not found: {contract_path}")

    contract = load_json(contract_path)
    validate_artifact("packet_pre_contract", contract)

    packet_dir = out_root / contract["packet_id"] / run_id
    required_files = sorted(set(contract["evidence"]["required_files"]))

    created = 0
    updated = 0
    skipped = 0

    for rel_path in required_files:
        target = packet_dir / rel_path
        status = write_if_changed(
            target, render_content(rel_path, contract, run_id, packet_dir)
        )
        if status == "created":
            created += 1
        elif status == "updated":
            updated += 1
        else:
            skipped += 1

    report = {
        "packet_id": contract["packet_id"],
        "run_id": run_id,
        "contract": str(contract_path),
        "output_dir": str(packet_dir),
        "required_files": required_files,
        "summary": {"created": created, "updated": updated, "skipped": skipped},
    }
    write_json(packet_dir / "golden_report.json", report)
    print(json.dumps(report, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
